---
title: "Untitled"
output: html_document
date: "2024-12-18"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown
```{r}
library(MRS)
require(phyloseq)

## Evaluation of MRS in terms of comparison between Healthy and Nonhealthy ##
## using ANCOMBC method and Shannon index
discovery=GMHI[[1]];
validation=GMHI[[2]];

res=MRS(discovery, validation, GroupID="Group", DA.method="ancombc", measurement="shannon")
 AUC=res[[3]]

 ## using ALDEx2 method and Shannon index

res=MRS(discovery, validation, GroupID="Group", DA.method="ALDEx2", measurement="shannon")
AUC=res[[3]]

## Evaluation of MRS in terms of comparison between Healthy and a specific disease ##
## Healthy vs. CA

discovery.sub=prune_samples(sample_data(discovery)$Group1 %in% c("Healthy","CA"),discovery)
validation.sub=prune_samples(sample_data(validation)$Group1 %in% c("Healthy","CA"),validation)

res=MRS(discovery.sub, validation.sub, GroupID="Group", DA.method="ALDEx2", measurement="shannon")
AUC=res[[3]]
```

